export const LOAD_CHANNELS = 'LOAD_CHANNELS';
export const SET_VISIBLE_CHANNELS = 'SET_VISIBLE_CHANNELS';
export const SET_VISIBLE_FAVORITES = 'SET_VISIBLE_FAVORITES';
export const SET_ACTIVE_CHANNEL = 'SET_ACTIVE_CHANNEL';
export const SET_ACTIVE_PANEL = 'SET_ACTIVE_PANEL';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';
export const SET_ACTIVE_FAVORITE = 'SET_ACTIVE_FAVORITE';
